-- ======================================================================
-- Schema — restore this FIRST, then 02-data.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (651533a)
-- Source schema     : public
-- Snapshot taken at : 2026-08-25 16:40:04.161064+00
--
-- FOREIGN KEYS ARE NOT IN THIS FILE. They are at the end of 02-data.sql,
-- after the rows, so the data can load in any order.
-- ======================================================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;

CREATE TYPE "ApprovalDecision" AS ENUM (
    'Approve',
    'Return',
    'Refuse'
);
CREATE TYPE "CreditSource" AS ENUM (
    'StripeCharge',
    'ManualTopUp',
    'ModelUsage',
    'ChatUsage',
    'Refund'
);
CREATE TYPE "EvidenceKind" AS ENUM (
    'Text',
    'File',
    'Url',
    'TestRun',
    'Attestation',
    'ExternalRef'
);
CREATE TYPE "MissionStatus" AS ENUM (
    'Draft',
    'InDiscovery',
    'InReadiness',
    'InWorkflow',
    'InGovernance',
    'InBuild',
    'AwaitingApproval',
    'Paused',
    'Blocked',
    'Rejected',
    'Completed',
    'WalkedAway',
    'RolledBack'
);
CREATE TYPE "ObjectionResolution" AS ENUM (
    'Overruled',
    'CarriedForward',
    'OwnerResolved',
    'Closed'
);
CREATE TYPE "OracleRole" AS ENUM (
    'NeedOracle',
    'ReadinessOracle',
    'WorkflowOracle',
    'GovernanceOracle',
    'BuildOracle',
    'ElderOracle'
);
CREATE TYPE "ReleaseActor" AS ENUM (
    'AIOnly',
    'Human',
    'Hybrid'
);
CREATE TYPE "RunStatus" AS ENUM (
    'Pending',
    'Running',
    'Succeeded',
    'Failed',
    'WalkedAway'
);
CREATE TYPE "SpecialistRole" AS ENUM (
    'Risk',
    'Demand',
    'Growth',
    'Competition',
    'Money'
);
CREATE TYPE "StageName" AS ENUM (
    'Discovery',
    'Readiness',
    'Workflow',
    'Governance',
    'SoftwareBuild'
);
CREATE TYPE "TestimonialSector" AS ENUM (
    'FinancialServices',
    'Insurance',
    'PublicSector',
    'Healthcare'
);
CREATE TYPE "ToolDecision" AS ENUM (
    'Approved',
    'Denied'
);
CREATE TYPE "ToolScope" AS ENUM (
    'Internal',
    'External'
);
CREATE TYPE "Verdict" AS ENUM (
    'Build',
    'TestFirst',
    'WalkAway'
);
CREATE TYPE "WorkItemStatus" AS ENUM (
    'Open',
    'InProgress',
    'InTest',
    'Rework',
    'Passed',
    'Failed',
    'Deferred'
);
CREATE TABLE "Approval" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    "gateIndex" integer NOT NULL,
    "stageHandoffId" text NOT NULL,
    "approverUserId" text,
    decision "ApprovalDecision" NOT NULL,
    "reasonCode" text NOT NULL,
    "reasonText" text NOT NULL,
    "supersedesApprovalId" text,
    "replayOfApprovalId" text,
    at timestamp(3) without time zone NOT NULL
);
CREATE TABLE "ApprovalActorTag" (
    id text NOT NULL,
    "approvalId" text NOT NULL,
    "actorKind" text NOT NULL,
    "actorLabel" text,
    "taggedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "ChatUsageRecord" (
    id text NOT NULL,
    scope text NOT NULL,
    "companyId" text,
    "missionId" text,
    "messageCount" integer NOT NULL,
    model text NOT NULL,
    "costCents" integer NOT NULL,
    "unknownCost" boolean NOT NULL,
    "windowStart" timestamp(3) without time zone NOT NULL,
    "windowEnd" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "CouncilRun" (
    id text NOT NULL,
    "leadId" text NOT NULL,
    status "RunStatus" NOT NULL,
    verdict "Verdict",
    "startedAt" timestamp(3) without time zone NOT NULL,
    "finishedAt" timestamp(3) without time zone,
    error text
);
CREATE TABLE "CreditLedgerEntry" (
    id text NOT NULL,
    "companyId" text NOT NULL,
    "amountCents" integer NOT NULL,
    source "CreditSource" NOT NULL,
    attribution jsonb,
    at timestamp(3) without time zone NOT NULL
);
CREATE TABLE "EvidenceItem" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    "attachedToStageHandoffId" text,
    kind "EvidenceKind" NOT NULL,
    ref text NOT NULL,
    label text NOT NULL,
    "capturedAt" timestamp(3) without time zone NOT NULL,
    "capturedById" text NOT NULL
);
CREATE TABLE "Lead" (
    id text NOT NULL,
    brief text NOT NULL,
    email text,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "notifiedAt" timestamp(3) without time zone,
    source text,
    payload text,
    notes text
);
CREATE TABLE "Mission" (
    id text NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    intake text NOT NULL,
    "normalizedNeed" text NOT NULL,
    status "MissionStatus" NOT NULL,
    "currentStageIndex" integer NOT NULL,
    "currentDraftVersion" integer,
    confidence double precision NOT NULL,
    "pausedAt" timestamp(3) without time zone,
    "completedAt" timestamp(3) without time zone,
    "rolledBackAt" timestamp(3) without time zone,
    "previousStatus" "MissionStatus",
    "createdById" text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "domainTags" text[],
    "intakeStructured" jsonb,
    "releaseReadoutAt" timestamp(3) without time zone
);
CREATE TABLE "MissionAudit" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    event text NOT NULL,
    payload jsonb NOT NULL,
    at timestamp(3) without time zone NOT NULL,
    "actorId" text,
    "missionVersionAtEvent" integer NOT NULL
);
CREATE TABLE "MissionOracleAssignment" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    role "OracleRole" NOT NULL,
    "userId" text NOT NULL,
    "appointedById" text NOT NULL,
    "appointedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "ModelUsageRecord" (
    id text NOT NULL,
    "missionId" text,
    "taskId" text,
    provider text NOT NULL,
    model text NOT NULL,
    "promptTokens" integer NOT NULL,
    "completionTokens" integer NOT NULL,
    "costCents" integer NOT NULL,
    "unknownCost" boolean NOT NULL,
    "attributedActor" text NOT NULL,
    "occurredAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "Objection" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    "stageHandoffId" text NOT NULL,
    "raisedByRole" text NOT NULL,
    text text NOT NULL,
    "evidenceRefId" text,
    "raisedAt" timestamp(3) without time zone NOT NULL,
    resolution "ObjectionResolution",
    "resolutionText" text
);
CREATE TABLE "ReleaseSource" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    actor "ReleaseActor" NOT NULL,
    "decidedById" text,
    "draftCapturedAt" timestamp(3) without time zone NOT NULL,
    "releasedAt" timestamp(3) without time zone NOT NULL,
    "reasonText" text
);
CREATE TABLE "StageHandoff" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    stage "StageName" NOT NULL,
    version integer NOT NULL,
    "parentVersionId" text,
    "correctionOfId" text,
    "supersededById" text,
    "replayOfMissionId" text,
    payload jsonb NOT NULL,
    confidence double precision NOT NULL,
    "missingEvidence" jsonb NOT NULL,
    "toolRefs" text[],
    "producedByToolActionId" text,
    "gateIndexThatApproves" integer NOT NULL,
    "invalidationReasonCode" text,
    "createdById" text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "StageHandoffSpecialistAttester" (
    id text NOT NULL,
    "handoffId" text NOT NULL,
    "userId" text NOT NULL,
    role "SpecialistRole" NOT NULL,
    "signedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "Testimonial" (
    id text NOT NULL,
    sector "TestimonialSector" NOT NULL,
    quote text NOT NULL,
    "attributedRole" text NOT NULL,
    organisation text NOT NULL,
    contact text,
    "quoteDate" timestamp(3) without time zone NOT NULL,
    published boolean NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "ToolAction" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    tool text NOT NULL,
    scope "ToolScope" NOT NULL,
    payload jsonb NOT NULL,
    "requestedById" text NOT NULL,
    "decidedById" text,
    decision "ToolDecision",
    "decisionReasonCode" text,
    "requiresGateApproval" boolean NOT NULL,
    "approvedGateIndex" integer,
    "decidedAt" timestamp(3) without time zone,
    "rejectedAt" timestamp(3) without time zone,
    "executedAt" timestamp(3) without time zone,
    "resultRef" text,
    "rollbackOfToolActionId" text,
    "producedStageHandoffId" text,
    "createdAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE "WorkItem" (
    id text NOT NULL,
    "missionId" text NOT NULL,
    "parentStageHandoffId" text NOT NULL,
    title text NOT NULL,
    scope text NOT NULL,
    "acceptanceCriteria" text NOT NULL,
    "ownerUserId" text,
    status "WorkItemStatus" NOT NULL,
    "openedAt" timestamp(3) without time zone NOT NULL,
    "closedAt" timestamp(3) without time zone,
    "testEvidenceRefIds" text[],
    "supersededById" text
);
CREATE TABLE account (
    id text NOT NULL,
    "accountId" text NOT NULL,
    "providerId" text NOT NULL,
    "userId" text NOT NULL,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamp(3) without time zone,
    "refreshTokenExpiresAt" timestamp(3) without time zone,
    scope text,
    password text,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE session (
    id text NOT NULL,
    "expiresAt" timestamp(3) without time zone NOT NULL,
    token text NOT NULL,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "ipAddress" text,
    "userAgent" text,
    "impersonatedBy" text,
    "userId" text NOT NULL
);
CREATE TABLE "user" (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    "emailVerified" boolean NOT NULL,
    image text,
    role text,
    banned boolean,
    "banReason" text,
    "banExpires" timestamp(3) without time zone,
    "createdAt" timestamp(3) without time zone NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL
);
CREATE TABLE verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    "expiresAt" timestamp(3) without time zone NOT NULL,
    "createdAt" timestamp(3) without time zone,
    "updatedAt" timestamp(3) without time zone
);
ALTER TABLE "Approval" ALTER COLUMN at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ApprovalActorTag" ALTER COLUMN "taggedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ChatUsageRecord" ALTER COLUMN "unknownCost" SET DEFAULT false;
ALTER TABLE "CouncilRun" ALTER COLUMN status SET DEFAULT 'Pending'::"RunStatus";
ALTER TABLE "CouncilRun" ALTER COLUMN "startedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "CreditLedgerEntry" ALTER COLUMN at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "EvidenceItem" ALTER COLUMN "capturedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Lead" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Mission" ALTER COLUMN status SET DEFAULT 'Draft'::"MissionStatus";
ALTER TABLE "Mission" ALTER COLUMN "currentStageIndex" SET DEFAULT 0;
ALTER TABLE "Mission" ALTER COLUMN confidence SET DEFAULT 0;
ALTER TABLE "Mission" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "MissionAudit" ALTER COLUMN at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "MissionOracleAssignment" ALTER COLUMN "appointedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ModelUsageRecord" ALTER COLUMN "unknownCost" SET DEFAULT false;
ALTER TABLE "ModelUsageRecord" ALTER COLUMN "occurredAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Objection" ALTER COLUMN "raisedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ReleaseSource" ALTER COLUMN "releasedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "StageHandoff" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "StageHandoffSpecialistAttester" ALTER COLUMN "signedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Testimonial" ALTER COLUMN published SET DEFAULT false;
ALTER TABLE "Testimonial" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ToolAction" ALTER COLUMN "requiresGateApproval" SET DEFAULT false;
ALTER TABLE "ToolAction" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "WorkItem" ALTER COLUMN status SET DEFAULT 'Open'::"WorkItemStatus";
ALTER TABLE "WorkItem" ALTER COLUMN "openedAt" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "user" ALTER COLUMN role SET DEFAULT 'user'::text;
ALTER TABLE "user" ALTER COLUMN banned SET DEFAULT false;
ALTER TABLE "Approval" ADD CONSTRAINT "Approval_pkey" PRIMARY KEY (id);
ALTER TABLE "ApprovalActorTag" ADD CONSTRAINT "ApprovalActorTag_pkey" PRIMARY KEY (id);
ALTER TABLE "ChatUsageRecord" ADD CONSTRAINT "ChatUsageRecord_pkey" PRIMARY KEY (id);
ALTER TABLE "CouncilRun" ADD CONSTRAINT "CouncilRun_pkey" PRIMARY KEY (id);
ALTER TABLE "CreditLedgerEntry" ADD CONSTRAINT "CreditLedgerEntry_pkey" PRIMARY KEY (id);
ALTER TABLE "EvidenceItem" ADD CONSTRAINT "EvidenceItem_pkey" PRIMARY KEY (id);
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_pkey" PRIMARY KEY (id);
ALTER TABLE "Mission" ADD CONSTRAINT "Mission_pkey" PRIMARY KEY (id);
ALTER TABLE "MissionAudit" ADD CONSTRAINT "MissionAudit_pkey" PRIMARY KEY (id);
ALTER TABLE "MissionOracleAssignment" ADD CONSTRAINT "MissionOracleAssignment_pkey" PRIMARY KEY (id);
ALTER TABLE "ModelUsageRecord" ADD CONSTRAINT "ModelUsageRecord_pkey" PRIMARY KEY (id);
ALTER TABLE "Objection" ADD CONSTRAINT "Objection_pkey" PRIMARY KEY (id);
ALTER TABLE "ReleaseSource" ADD CONSTRAINT "ReleaseSource_pkey" PRIMARY KEY (id);
ALTER TABLE "StageHandoff" ADD CONSTRAINT "StageHandoff_pkey" PRIMARY KEY (id);
ALTER TABLE "StageHandoffSpecialistAttester" ADD CONSTRAINT "StageHandoffSpecialistAttester_pkey" PRIMARY KEY (id);
ALTER TABLE "Testimonial" ADD CONSTRAINT "Testimonial_pkey" PRIMARY KEY (id);
ALTER TABLE "ToolAction" ADD CONSTRAINT "ToolAction_pkey" PRIMARY KEY (id);
ALTER TABLE "WorkItem" ADD CONSTRAINT "WorkItem_pkey" PRIMARY KEY (id);
ALTER TABLE account ADD CONSTRAINT account_pkey PRIMARY KEY (id);
ALTER TABLE session ADD CONSTRAINT session_pkey PRIMARY KEY (id);
ALTER TABLE "user" ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE verification ADD CONSTRAINT verification_pkey PRIMARY KEY (id);
CREATE INDEX "ApprovalActorTag_actorKind_idx" ON "ApprovalActorTag" USING btree ("actorKind");
CREATE INDEX "ApprovalActorTag_approvalId_idx" ON "ApprovalActorTag" USING btree ("approvalId");
CREATE INDEX "Approval_missionId_at_idx" ON "Approval" USING btree ("missionId", at);
CREATE INDEX "Approval_missionId_gateIndex_idx" ON "Approval" USING btree ("missionId", "gateIndex");
CREATE UNIQUE INDEX "Approval_missionId_gateIndex_stageHandoffId_key" ON "Approval" USING btree ("missionId", "gateIndex", "stageHandoffId");
CREATE INDEX "ChatUsageRecord_companyId_windowStart_idx" ON "ChatUsageRecord" USING btree ("companyId", "windowStart");
CREATE INDEX "ChatUsageRecord_scope_windowStart_idx" ON "ChatUsageRecord" USING btree (scope, "windowStart");
CREATE INDEX "CouncilRun_leadId_idx" ON "CouncilRun" USING btree ("leadId");
CREATE INDEX "CouncilRun_status_idx" ON "CouncilRun" USING btree (status);
CREATE INDEX "CreditLedgerEntry_companyId_at_idx" ON "CreditLedgerEntry" USING btree ("companyId", at);
CREATE INDEX "CreditLedgerEntry_source_idx" ON "CreditLedgerEntry" USING btree (source);
CREATE INDEX "EvidenceItem_missionId_capturedAt_idx" ON "EvidenceItem" USING btree ("missionId", "capturedAt");
CREATE INDEX "EvidenceItem_missionId_idx" ON "EvidenceItem" USING btree ("missionId");
CREATE INDEX "Lead_createdAt_idx" ON "Lead" USING btree ("createdAt");
CREATE INDEX "MissionAudit_missionId_at_idx" ON "MissionAudit" USING btree ("missionId", at);
CREATE INDEX "MissionOracleAssignment_missionId_idx" ON "MissionOracleAssignment" USING btree ("missionId");
CREATE UNIQUE INDEX "MissionOracleAssignment_missionId_role_key" ON "MissionOracleAssignment" USING btree ("missionId", role);
CREATE INDEX "MissionOracleAssignment_userId_idx" ON "MissionOracleAssignment" USING btree ("userId");
CREATE INDEX "Mission_createdById_idx" ON "Mission" USING btree ("createdById");
CREATE UNIQUE INDEX "Mission_slug_key" ON "Mission" USING btree (slug);
CREATE INDEX "Mission_status_idx" ON "Mission" USING btree (status);
CREATE INDEX "ModelUsageRecord_missionId_occurredAt_idx" ON "ModelUsageRecord" USING btree ("missionId", "occurredAt");
CREATE INDEX "ModelUsageRecord_model_idx" ON "ModelUsageRecord" USING btree (model);
CREATE INDEX "ModelUsageRecord_occurredAt_idx" ON "ModelUsageRecord" USING btree ("occurredAt");
CREATE INDEX "Objection_missionId_raisedAt_idx" ON "Objection" USING btree ("missionId", "raisedAt");
CREATE INDEX "ReleaseSource_actor_idx" ON "ReleaseSource" USING btree (actor);
CREATE UNIQUE INDEX "ReleaseSource_missionId_key" ON "ReleaseSource" USING btree ("missionId");
CREATE INDEX "ReleaseSource_releasedAt_idx" ON "ReleaseSource" USING btree ("releasedAt");
CREATE INDEX "StageHandoffSpecialistAttester_handoffId_idx" ON "StageHandoffSpecialistAttester" USING btree ("handoffId");
CREATE UNIQUE INDEX "StageHandoffSpecialistAttester_handoffId_userId_key" ON "StageHandoffSpecialistAttester" USING btree ("handoffId", "userId");
CREATE INDEX "StageHandoff_missionId_createdAt_idx" ON "StageHandoff" USING btree ("missionId", "createdAt");
CREATE INDEX "StageHandoff_missionId_stage_idx" ON "StageHandoff" USING btree ("missionId", stage);
CREATE INDEX "StageHandoff_missionId_stage_version_idx" ON "StageHandoff" USING btree ("missionId", stage, version);
CREATE INDEX "Testimonial_published_sector_idx" ON "Testimonial" USING btree (published, sector);
CREATE INDEX "ToolAction_missionId_createdAt_idx" ON "ToolAction" USING btree ("missionId", "createdAt");
CREATE INDEX "ToolAction_missionId_idx" ON "ToolAction" USING btree ("missionId");
CREATE INDEX "WorkItem_missionId_parentStageHandoffId_idx" ON "WorkItem" USING btree ("missionId", "parentStageHandoffId");
CREATE INDEX "WorkItem_missionId_status_idx" ON "WorkItem" USING btree ("missionId", status);
CREATE UNIQUE INDEX session_token_key ON session USING btree (token);
CREATE UNIQUE INDEX user_email_key ON "user" USING btree (email);
