-- ======================================================================
-- Data — restore this AFTER 01-schema.sql
--
-- Generated by Polsia from your app database.
-- Source PostgreSQL : 16.15 (651533a)
-- Source schema     : public
-- Snapshot taken at : 2026-08-25 16:40:04.161064+00
--
-- Foreign keys are added at the END of this file, once every row is in place,
-- so table and row order does not matter.
-- ======================================================================
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
SET DateStyle = 'ISO, MDY';
SET IntervalStyle = 'postgres';
SET TimeZone = 'UTC';
SET search_path TO public;


-- Approval

-- ApprovalActorTag

-- ChatUsageRecord

-- CouncilRun

-- CreditLedgerEntry

-- EvidenceItem

-- Lead

-- Mission

-- MissionAudit

-- MissionOracleAssignment

-- ModelUsageRecord

-- Objection

-- ReleaseSource

-- StageHandoff

-- StageHandoffSpecialistAttester

-- Testimonial

-- ToolAction

-- WorkItem

-- account

-- session

-- user

-- verification
-- Foreign keys — added last, so the rows above could load in any order.
ALTER TABLE account ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE session ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- Give the planner statistics to work with.
ANALYZE;
